# Generated by Django 5.1.1 on 2024-10-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('learning_duration', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
