# Generated by Django 5.1.1 on 2024-10-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('webinar_title', models.CharField(max_length=200)),
                ('webinar_date', models.DateField()),
                ('slot_1', models.BooleanField(default=False)),
                ('slot_2', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('Social Media', 'Social Media'), ('Word of Mouth', 'Word of Mouth'), ('Advertisement', 'Advertisement'), ('Other', 'Other')], max_length=100)),
            ],
        ),
    ]
