# Generated by Django 5.1.1 on 2024-10-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
                ('institution', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
                ('field_of_study', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('desired_position', models.CharField(max_length=255)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.FileField(upload_to='cover_letters/')),
            ],
        ),
    ]
