# Generated by Django 5.1.1 on 2024-10-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('educational_institution', models.CharField(max_length=255)),
                ('year_of_graduation', models.IntegerField()),
                ('field_of_study', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
